from __future__ import annotations

import os
SEARCH_SETTLE_SECONDS = float(os.environ.get("FAKTURAMA_ENTITY_RESOLUTION_SEARCH_SETTLE_SECONDS", "1.0"))

DIALOG_TIMEOUT_SECONDS = float(os.environ.get("FAKTURAMA_ENTITY_RESOLUTION_DIALOG_TIMEOUT_SECONDS", "5.0"))

COMBO_POPUP_SETTLE_TIMEOUT_SECONDS = float(
    os.environ.get("FAKTURAMA_ENTITY_RESOLUTION_COMBO_POPUP_SETTLE_TIMEOUT_SECONDS", "1.5")
)
